### ISSUE TITLE
A port for Linux?

### ISSUE THREAD

**Issue by CavaleriOmar** [vddCore/Zephyrus-Control-Center#1]
It's a very impressive tool, and it would be really cool to have it on Linux as well

**Comment by vddCore** [comment]
Linux version is not planned at the moment. There are a few reasons for that, one of them is outlined in the [README.md](https://github.com/vddCore/Zephyrus-Control-Center/blob/master/README.md#absolutely-no-guarantee-itll-work-for-you), others include:

1. I don't use Linux anymore, as of late, so it makes no sense for me to put an effort into figuring out a Linux port.
2. Vast majority of the infrastructure subsystems [are made with Windows in mind](https://github.com/vddCore/Zephyrus-Control-Center/tree/master/Slate/Infrastructure) and it is non-trivial to find Linux-equivalents for these system calls. It is possible to extract and re-use most of the ASUS-specific logic in another project, though.

Sorry I couldn't be more helpful. Have a good day!
