### ISSUE TITLE
Problems building

### ISSUE THREAD

**Issue by Sneeshah** [vddCore/Zephyrus-Control-Center#2]
Disclaimer: I am not experienced with c# or visual studio at all, so the solution to my problem might be super simple.

I cloned the project in visual studio and tried to build "Slate.sln" but got this error that throws me off a bit:

Error	NU1104	Unable to find project 'C:\Users\...\Zephyrus-Control-Center1\Starlight\Starlight\Starlight.csproj'. Check that the project reference is valid and that the project file exists.	
	
I 100 % know that there is no "Starlight" folder at said location, I guess I have to fix the dependency on starlight but how do I do that? Sorry again if it is a simple question - I was not able to find a solution to my problem yet. (Just as I wrote that I got an idea - do I have to add the starlight, avalonia and glitonea folders as seperate projects and reference them?)

**Comment by vddCore** [comment]
Starlight is installed as a submodule. Make sure you clone recursively, i.e.: `git clone https://github.com/vddCore/Zephyrus-Control-Center.git --recursive`.

**Comment by Sneeshah** [comment]
Oh yeah that makes a lot of sense, thanks for the quick reply!
